DNA = 'AGGAAACAACGTTAGCACCCGACGACGTAGGATCTGTCATCATAAGAAAACTCTCTGAATGTGCACTAGCATTCAACATGGTATGCTATCCTGTTATTGGATCGTCTTTCCATCTGCCGGTGCATAATTAGTCGCTTTTATCGGGGTTTCAAGCAGAAGTGTCGGTGAAAGGTTTGGACCCAAAGAAGTTCGCAGACCCTACTGATGGTTGGATATTGCGGTACTCTAAGGATAAGCATGCGTATTTACTCTCGTAGATCTGTACGATGCATTTTTATGCGTTAGTACATATGCTCTAACGAGAGACGGTAGGGTAAGTCATCGATGGGCAGGCCTGCACATAGCAAGTTTAAATCTGTATGCGGTCAATTGCGTCCAGGGCAGTGTGACTTCTTACTGTCGGCGCAAACGACCGCCGCGAACGCCGTGCGTCCCCGGTTACTACATCGGTTGATACGATGATTATTGCCCGAAATTCCGATGCTCTGGCCTTCTAGAATTCTAATTACGAGGGAAGTATAATCTCTCATTGTTGTAGTATCAGCCGGGTCAATATTTGCGGTTACGCACGTAGCGCCTAAGCCGGTTCGGTAACAGGTGAATCCGCGTGTAAACTCAGTGTGACGCTCGTCGGATTCCATGTCAGTCCAGCTTTTCAGGCTGGCAACGCGTGACAAATCGTTGTTTTGCTATACTTGTAAGATTTACACCCGTATTTTTCTCGTTATTCATATCGATGCCAAGTAAATATCCTAATCTTATTCATGGTCGTATTACATCCGGACGATGGTCCTGGATTCGGAACCGGATTACCCAGGATTCTAGATTCTGCAA'

d_DNA = dict()

for i in DNA:
    if i not in d_DNA:
        d_DNA[i] = 0
    d_DNA[i] += 1

print(d_DNA['A'] , end = ' ')
print(d_DNA['C'], end = ' ')
print(d_DNA['G'], end = ' ')
print(d_DNA['T'], end = ' ')